# Generated by Django 4.0.3 on 2022-03-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha_añadido',
            new_name='fecha_add',
        ),
    ]
